### ISSUE TITLE
VIP protocol not translated

### ISSUE THREAD

**Issue by shmoeshmeps** [himalayanBuddy/ACEPARSER#1]
An initial test case I did had a UDP port on a VIP. This was not picked up when I ran the tool - instead TCP was used and output as the new VIP config.

I traced this to a typo in create_f5_configs.py where virtual_server_protocol should be virtualserver_protocol. Worked when I fixed the typo. Will see if I can do a commit shortly...

**Comment by himalayanBuddy** [comment]
Thanks. The pull request has been merged to the master. Closing this issue.
